cmake_minimum_required(VERSION 3.22)
project(stm_sdram_portable_tests C CXX)
enable_testing()
add_subdirectory(../.. component)
add_executable(sdram_portable test_core.c headers.cpp)
target_link_libraries(sdram_portable PRIVATE stm_sdram)
target_compile_features(sdram_portable PRIVATE c_std_11 cxx_std_17)
if(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
    target_compile_options(stm_sdram PRIVATE -Wall -Wextra -Werror)
    target_compile_options(sdram_portable PRIVATE -Wall -Wextra -Werror)
endif()
add_test(NAME sdram_portable COMMAND sdram_portable)
